app:
  host: "localhost"
  port: "9000"

fileStorage:
  origin: "http://localhost:5050"

hasherService:
  host: "localhost:8090"

userService:
  host: "localhost:8080"

frontend:
  origin: "http://localhost:5173"
